### ISSUE TITLE
ActiveSupport in Phase 3

### ISSUE THREAD

**Issue by aplarson** [appacademy/rails_lite#16]
I had a student run into a `uninitialized constant ActiveSupport::Autoload (NameError)` on running the provided file for phase 3. This seems to be a known danger of independently calling `require "active_support/core_ext"`, which (according to the discussion [here](https://github.com/rails/rails/issues/14664)) loads files in an unpredictable order, which will sometimes succeed and sometimes fail depending on the order. The fix was to add `require "active_support"` before `require "active_support/core_ext"`.

**Comment by aplarson** [comment]
Looks like @w1zeman1p got to it already

**Comment by w1zeman1p** [comment]
:)
