### ISSUE TITLE
Adding Bonus Specs + Servers to Skeleton

### ISSUE THREAD

**Issue by dcurletti** [appacademy/rails_lite#18]
It would be awesome if the bonus specs for the rails_lite project were included in the skeleton of the project.  I suggest this only because a number of people arrived to the bonus and were not aware that there were more spec files.  If this was done purposefully, please ignore.
Thanks.

**Comment by w1zeman1p** [comment]
Yeah. Good suggestion. We did talk about that and decided that if people made it to bonus than it would be good for them to proceed without specs.
